server {
    listen 80;
    server_name _; # Change this to your domain if you have one, e.g., example.com

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        root /var/www/my_django_app;
    }

    location /media/ {
        root /var/www/my_django_app;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/my_django_app/server.sock;
    }
}
